obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[0.22, 0.3], [-0.22, 0.3], [-0.22, -0.3], [0.22, -0.3]]

inflation_radius: 0.6
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
